const player={energy:80,hunger:70,mood:75,money:50,reputation:50,school:70};
const calendar={day:1,month:9,year:2026};
let gameTime={hour:7,minute:0};
const characterData={name:"Новый персонаж",style:"heart"};
const styles={
 heart:{name:"Уютный",src:"assets/character_heart.png"},
 black:{name:"Dark",src:"assets/character_black.png"},
 pink:{name:"Pink",src:"assets/character_pink.png"}
};
const $=id=>document.getElementById(id);
const clock=$('clock'),dayElement=$('day'),energyElement=$('energy'),hungerElement=$('hunger'),moodElement=$('mood'),moneyElement=$('money'),messageElement=$('message'),character=$('character');
const positions={bed:{left:"22%",top:"70%"},computer:{left:"72%",top:"65%"},plant:{left:"85%",top:"25%"},window:{left:"25%",top:"30%"},door:{left:"86%",top:"78%"}};
function clampStats(){player.energy=Math.max(0,Math.min(100,player.energy));player.hunger=Math.max(0,Math.min(100,player.hunger));player.mood=Math.max(0,Math.min(100,player.mood));player.school=Math.max(0,Math.min(100,player.school));player.reputation=Math.max(0,Math.min(100,player.reputation));player.money=Math.max(0,player.money)}
function dateText(){const d=new Date(calendar.year,calendar.month-1,calendar.day);const days=["Воскресенье","Понедельник","Вторник","Среда","Четверг","Пятница","Суббота"];return `${days[d.getDay()]}, ${calendar.day}.${String(calendar.month).padStart(2,'0')}.${calendar.year}`}
function updateInterface(){clock.textContent=`${String(gameTime.hour).padStart(2,'0')}:${String(gameTime.minute).padStart(2,'0')}`;dayElement.textContent=dateText();energyElement.textContent=Math.round(player.energy);hungerElement.textContent=Math.round(player.hunger);moodElement.textContent=Math.round(player.mood);moneyElement.textContent=Math.round(player.money);updateRoomCharacter()}
function addTime(minutes){gameTime.minute+=minutes;while(gameTime.minute>=60){gameTime.minute-=60;gameTime.hour++}while(gameTime.hour>=24){gameTime.hour-=24;calendar.day++;messageElement.textContent='🌅 Наступил новый день!'}while(calendar.day>new Date(calendar.year,calendar.month,0).getDate()){calendar.day-=new Date(calendar.year,calendar.month,0).getDate();calendar.month++;if(calendar.month>12){calendar.month=1;calendar.year++}}updateInterface()}
function moveCharacter(object){if(!positions[object])return;character.classList.add('moving');character.style.left=positions[object].left;character.style.top=positions[object].top;setTimeout(()=>character.classList.remove('moving'),700)}
function interact(object){moveCharacter(object);if(object==='bed'){addTime(120);player.energy+=35;player.hunger-=10;player.mood+=5;messageElement.textContent='💤 Ты поспал два часа.'}else if(object==='computer'){addTime(30);player.energy-=5;player.mood+=8;messageElement.textContent='🖥️ Ты посидел за компьютером.'}else if(object==='plant'){addTime(5);player.mood+=4;messageElement.textContent='🪴 Ты полил растение.'}else if(object==='window'){addTime(5);player.mood+=3;messageElement.textContent='🪟 Ты посмотрел в окно.'}else if(object==='door'){addTime(10);messageElement.textContent='🚪 Ты подошёл к двери.'}else if(object==='character'){openCharacterEditor()}clampStats();updateInterface()}
function gameAction(action){if(action==='sleep'){interact('bed');return}if(action==='eat'){if(player.money<5){messageElement.textContent='💶 Недостаточно денег.';return}addTime(25);player.money-=5;player.hunger+=30;player.mood+=5;messageElement.textContent='🍳 Ты поел.'}else if(action==='wash'){addTime(15);player.energy-=4;player.mood+=10;messageElement.textContent='🚿 Ты привёл себя в порядок.'}else if(action==='rest'){addTime(30);player.energy+=8;player.hunger-=3;player.mood+=5;messageElement.textContent='🪑 Ты немного отдохнул.'}clampStats();updateInterface()}
function work(){if(gameTime.hour<14){messageElement.textContent='⏰ Смена ещё не началась.';return}if(gameTime.hour>=17){messageElement.textContent='❌ Смена уже закончилась.';return}addTime(180);player.money+=30;player.energy-=15;player.mood-=5;player.reputation+=2;clampStats();messageElement.textContent='💼 Смена закончена! +30€';updateInterface()}
function saveGame(){localStorage.setItem('tinylifeSave',JSON.stringify({player,calendar,gameTime,characterData}));messageElement.textContent='💾 Игра сохранена!'}
function loadGame(){const raw=localStorage.getItem('tinylifeSave');if(!raw)return;try{const s=JSON.parse(raw);Object.assign(player,s.player);Object.assign(calendar,s.calendar);Object.assign(gameTime,s.gameTime);Object.assign(characterData,s.characterData);clampStats()}catch(e){console.warn('Save error',e)}}
function updateRoomCharacter(){const src=styles[characterData.style]?.src||styles.heart.src;character.innerHTML=`<img src="${src}" alt="${characterData.name}">`}
function openCharacterEditor(){const modal=$('characterEditor');modal.classList.add('active');modal.setAttribute('aria-hidden','false');$('characterName').value=characterData.name;$('previewName').textContent=characterData.name;$('saveState').textContent='Не сохранено';renderStyles()}
function closeCharacterEditor(){$('characterEditor').classList.remove('active');$('characterEditor').setAttribute('aria-hidden','true')}
function renderStyles(){const box=$('styleChoices');box.innerHTML='';Object.entries(styles).forEach(([key,s])=>{const b=document.createElement('button');b.className='choice'+(key===characterData.style?' selected':'');b.innerHTML=`<img src="${s.src}" alt=""><b>${s.name}</b>`;b.onclick=()=>{characterData.style=key;renderStyles();updatePreview()};box.appendChild(b)});updatePreview()}
function updatePreview(){const src=styles[characterData.style].src;$('characterPreview').innerHTML=`<img src="${src}" alt="">`;$('previewName').textContent=characterData.name||'Новый персонаж'}
function saveCharacter(){const n=$('characterName').value.trim();if(n)characterData.name=n;localStorage.setItem('tinyLifeCharacter',JSON.stringify(characterData));$('saveState').textContent='Сохранено ✓';updatePreview();updateRoomCharacter();messageElement.textContent=`👤 Персонаж "${characterData.name}" сохранён!`;setTimeout(closeCharacterEditor,350)}

document.querySelectorAll('.action[data-action]').forEach(b=>b.addEventListener('click',()=>gameAction(b.dataset.action)));
document.querySelectorAll('.room-object').forEach(b=>b.addEventListener('click',()=>interact(b.dataset.object)));
$('workButton').addEventListener('click',work);$('characterButton').addEventListener('click',openCharacterEditor);$('closeEditor').addEventListener('click',closeCharacterEditor);$('saveCharacterButton').addEventListener('click',saveCharacter);$('saveGameButton').addEventListener('click',saveGame);$('characterName').addEventListener('input',()=>{characterData.name=$('characterName').value.trim()||'Новый персонаж';updatePreview()});
$('characterEditor').addEventListener('click',e=>{if(e.target.id==='characterEditor')closeCharacterEditor()});
loadGame();updateInterface();messageElement.textContent='🌷 Добро пожаловать в TinyLife 0.4.2!';
setInterval(()=>{addTime(5);player.energy-=0.2;player.hunger-=0.15;clampStats();updateInterface()},10000);
